### PR TITLE
Cedar.js

### PR DESCRIPTION
**Pull request by rvdkooy**
Opening the pull request for reviewing purposes (please do not merge yet)

Implemented:
- [x] Angular version of the command api
- [x] Gulp task to run the unittests

still to do:
- [ ] Create a test project that uses cedar.js to send commands to the server
- [ ] Implement a jquery version of the command api
- [ ] Create distribution versions through the build script (or its own)
- [ ] Configure npm publish (@damianh)

### CODE REVIEW

**Comment by damianh** [comment]
lovely!

**Comment by damianh** [comment]
Wait, shouldn't this PR be directed at https://github.com/damianh/Cedar.HttpCommandHandling ?

**Comment by rvdkooy** [comment]
oh really!
ok, no problem I will close the PR and implement it in Cedar.HttpCommandHandling.

**Comment by damianh** [comment]
Yeah it's where we already have the Javascript examples: https://github.com/damianh/Cedar.HttpCommandHandling/tree/master/src/Cedar.HttpCommandHandling.Example.JavaScript/wwwroot

**Pull request closed without merging**
